name: Nightly tests

on:
  schedule:
    - cron: '1 0 * * *'  # Run daily at 0:01 UTC

jobs:
  tests:
    if: github.repository_owner == 'Lexcere'  # run only when in Lexcere
    uses: ./.github/workflows/test.yaml