name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install -r requirement-dex.txt
      - name: Lint
        run: |
          flake8
      - name: Test
        run: |
          python -m pytest